# Generated by Django 4.2.11 on 2024-05-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_branch_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject_id',
        ),
    ]
