# Generated by Django 4.2.11 on 2024-05-05 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_student_subject_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Enrolment_no',
            new_name='enrolment_no',
        ),
    ]
