# Generated by Django 4.2.11 on 2024-05-06 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_faculty_coordinator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='coordinator',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.course'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='department_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.department'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='branch_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.branch'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.course'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='department_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.department'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='branch_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.branch'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'COORDINATOR'), (3, 'FACULTY'), (4, 'STUDENT')], max_length=50),
        ),
    ]
