# Generated by Django 4.2.11 on 2024-05-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_faculty_subject_id_coordinator_course_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='name',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
