# Generated by Django 4.2.11 on 2024-05-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_subject_name_subject_subject_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session_year',
            old_name='session_end',
            new_name='session_year_end',
        ),
        migrations.RenameField(
            model_name='session_year',
            old_name='session_start',
            new_name='session_year_start',
        ),
    ]
