# Generated by Django 4.2.11 on 2024-05-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_session_end_session_year_session_year_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
        migrations.AddField(
            model_name='department',
            name='department_name',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
