# Generated by Django 4.2.11 on 2024-05-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_attendance_attendance_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='branch_id',
        ),
    ]
