# Generated by Django 4.2.11 on 2024-05-14 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_faculty_branch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='branch_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.branch'),
        ),
        migrations.AddField(
            model_name='subject',
            name='faculty_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.faculty'),
        ),
    ]
