# Generated by Django 4.2.11 on 2024-05-14 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_subject_branch_id_alter_subject_faculty_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='branch_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.branch'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='faculty_id',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.faculty'),
        ),
    ]
