# Generated by Django 4.2.11 on 2024-05-14 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_subject_branch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='faculty_id',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.course'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.department'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
