# Generated by Django 4.2.11 on 2024-05-14 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_subject_faculty_id_alter_faculty_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='branch_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.branch'),
        ),
        migrations.AddField(
            model_name='subject',
            name='faculty_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.faculty'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.branch'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.course'),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.department'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.course'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.department'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=100),
        ),
    ]
